var lang = {

		//Login
		Login: "Đăng nhập",
		Username: "Tên đăng nhập",
		Password: "Mật khẩu",
		Welcome: "Chào",
		Logout: "Đăng xuất",

		//Menu
		Home: "Trang chủ",
		Reporting: "Báo cáo",
		Products: "Sản phẩm",
		Categories : "Danh mục",
		Employees: "Nhân viên",
		Settings: "Cài đặt",

		//Home
		Desk: "Bàn",
		Review: "Xem Lại",
		Address: "Địa Chỉ",
		Phone: "Điện Thoại",
		Fax: "Fax",
		TaxCode: "Mã số thuế",
		AccountInfo: "Thông Tin Tài Khoản",
		PrepairPrinting: "Chuẩn bị in",
		Edit: "Sửa",
		Del: "Xóa",
		IsServed: "PV",
		Serve: "Phục vụ",
		PrintSale: " In HĐ.BH",
		Customer: "Khách hàng",
		Day: "Ngày",
		Month: "tháng",
		Year: "năm",
		TaxRate: "Thuế suất GTGT",
		Tax: "Tiền Thuế GTGT",
		SubTotal: "Cộng",
		Total: "Tổng",
		Pay: "Thanh Toán",
		PrePaid : "Đặt cọc",
		Paid: "Đã trả",
		DueChange: "Còn lại",
		Sign: "Ký tên",
		Note: "Ghi chú",
		ServingEmployee: "Nhân viên phục vụ",
		CheckInTime: "Thời gian đặt: ",
		CheckOutTime: "Thời gian thanh toán : ",
		UpdatedTime: "Thời gian phục vụ",
		Time: "T.gian",
		MergeOrMove: "Chuyển/Gộp",
		MergeOrMoveText: "Số bàn chuyển tới/gộp",
		ExtraPaidPerItem: "Phụ thu 1 ly",
		ExtraPaid: "Tổng phụ thu",
		Add: "Thêm",

		//Products
		Search: "Tìm kiếm",
		Product: "Sản phẩm",
		Price: "Giá",
		Stock: "T.Kho",
		Unit: "ĐV",
		Units: "Đơn vị S.Phẩm",
		Qty: "S.Lg",
		Amount: "T.Tiền",
		Choose: "Chọn",
		No: "TT",
		Date: "Ngày",
		Del: "Xóa",
		Save: "Lưu",
		Cancel: "Hủy",
		Name: "Tên",
		IsFavorite: "Yêu thích",
		Image: "Hình ảnh",
		Id: "TT",
		Related: "Liên quan",
		NewProduct: "S.Phẩm mới",
		UploadImage: "Up ảnh",
		ChooseImage: "Chọn ảnh",

		//Categories
		Categories: "Danh mục",
		Category: "Danh mục",
		NewCategory: "D.Mục mới",

		//Employees
		NewEmployee: "N.Viên mới",
		AccessLevel: "Quyền",
		FirstName: "Họ",
		LastName: "Tên",
		Image: "Hình ảnh",
		Email: "Email",
		Phone: "Điện thoại",
		Birthday: "Ngày sinh",
		Address: "Địa chỉ",
		Delete: "Xóa",
		Admin: "Quản trị viên",
		Manager: "Quản lý",
		User: "Nhân viên",
		Cashier: "Thu ngân",
		Bartender: "Pha chế",
		SelectAccessLevel: "Chọn phân quyền",
		Region: "Khu vực",


		//Modal
		Message : "Thông báo",
		Close : "Đóng",

		//Settings
		NumOfDesks: "Số lượng bàn",
		Email: "Email",
		SendReport: "Gởi báo cáo qua email",

		//Report by desk
		ReportByDesk: "Tình trạng phục vụ",
		IdReceipt: "Mã hóa đơn",
		SubAmount: "Tiền",
		Back: "Quay lại",
		Quantity: "Số lượng",
		TotalReceipts: "Tổng số hóa đơn",
		Receipt: "Số hóa đơn",
		ExtraPaidPerItem: "Phụ thu 1 ly",
		ExtraPaid: "Tổng phụ thu",
		NumOfItems: "Tổng số ly",

		//Reporting:
		NumOfOrderItems: "Sồ lần đặt",
		NumOfItems: "Số ly",
		Today: "Hôm nay",
		ThisWeek: "Tuần này",
		ThisMonth: "Tháng này",

		//Message
		Error: "Lỗi thao tác",
		FailToLogin: "Sai tên đăng nhập hoặc mật khẩu",
		FailToAccess: "Tài khoản của bạn không có quyền truy cập chức năng này",
		SuccessToSaveSettings: "Lưu thành công cài đặt",
		FailToSaveSettings: "Lỗi khi lưu cài đặt",
		AccessDenied: "Truy cập chức năng bị từ chối",
		ItemsNotServed: "Vài thức uống chưa phục vụ!",
		ItemServed: "Món này đã phục vụ, không xóa được!",
};
